"""add session_id to chat_logs

Revision ID: 35f2369e5f29
Revises: e3b297c165fd
Create Date: 2026-06-09 18:54:30.300613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f2369e5f29'
down_revision: Union[str, Sequence[str], None] = 'e3b297c165fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('session_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_chat_logs_session_id'), 'chat_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_logs_session_id'), table_name='chat_logs')
    op.drop_column('chat_logs', 'session_id')
    # ### end Alembic commands ###
